# Generated by Django 5.0 on 2023-12-18 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите полное имя пользователя', max_length=200, verbose_name='Полное имя пользователя')),
                ('address', models.CharField(blank=True, help_text='Введите адрес пользователя', max_length=200, null=True, verbose_name='Адрес пользователя')),
                ('joined_on', models.DateTimeField(auto_now_add=True, help_text='Введите дату регистрации пользователя', verbose_name='Дата регистрации пользователя')),
                ('user', models.OneToOneField(help_text='Введите юзернейм пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзернейм пользователя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
    ]
