# Generated by Django 5.0 on 2023-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clonliner', '0002_alter_customer_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Введите дату регистрации пользователя', verbose_name='Дата регистрации пользователя'),
        ),
    ]
