# Generated by Django 5.0 on 2023-12-19 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clonliner', '0004_alter_customer_joined_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок объявления', max_length=200)),
                ('description', models.TextField(help_text='Введите описание объявления')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=10)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания объявления')),
                ('created_by', models.ForeignKey(help_text='Автор объявления', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_on'],
            },
        ),
    ]
