# Generated by Django 5.0 on 2023-12-20 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clonliner', '0008_remove_chat_user_1_remove_chat_user_2_chat_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Unseen')], default='unseen', help_text='Статус сообщения', max_length=10, verbose_name='Статус сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(help_text='Выберите чат', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Clonliner.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Введите текст сообщения', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='Введите отправителя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Введите время отправления', verbose_name='Время отправления'),
        ),
    ]
