# Generated by Django 5.0 on 2023-12-21 15:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clonliner', '0009_message_status_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Image 1'), (1, 'Image 2'), (2, 'Image 3'), (3, 'Image 4'), (4, 'Image 5')], help_text='Фотографии объявления', max_length=255, null=True, verbose_name='Фото'),
        ),
    ]
