# Generated by Django 5.0 on 2023-12-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clonliner', '0010_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотографии объявления', null=True, upload_to='post_photos', verbose_name='Фото'),
        ),
    ]
